### ISSUE TITLE
chef-load panics after getting a few 500 errors

### ISSUE THREAD

**Issue by irvingpop** [jeremiahsnapp/chef-load#11]
Observed on 2.0.0 and 2.1.0,  we've noticed that chef-load crashes after getting just a few 500s back:

```
2017-07-27T21:06:47Z chef-load5-3990 run_finished
Couldn't get node:  GET https://irving-backendless-chef-lb-1740202824.us-west-2.elb.amazonaws.com/organizations/irving/nodes/chef-load5-3993: 502
POST https://irving-backendless-chef-lb-1740202824.us-west-2.elb.amazonaws.com/organizations/irving/data-collector: 502
2017-07-27T21:06:47Z chef-load5-3991 run_finished
POST https://irving-backendless-chef-lb-1740202824.us-west-2.elb.amazonaws.com/organizations/irving/environments/_default/cookbook_versions: 502
GET https://irving-backendless-chef-lb-1740202824.us-west-2.elb.amazonaws.com/organizations/irving/search/node?q=%2A%253A%2A&sort=X_CHEF_id_CHEF_X+asc&start=0: 502
2017-07-27T21:06:47Z chef-load5-3994 run_started
POST https://irving-backendless-chef-lb-1740202824.us-west-2.elb.amazonaws.com/organizations/irving/data-collector: 404
2017-07-27T21:06:47Z chef-load5-3992 run_finished
2017-07-27T21:06:47Z chef-load5-3995 run_started
panic: assignment to entry in nil map

goroutine 14304 [running]:
main.chefClientRun(0xc4200c7360, 0xc420086480, 0xc4200152f0, 0xc42000e050, 0xc42000e058, 0xc42000e060, 0xc42000e068, 0xc42000e070, 0xc42000e078, 0xc42000e080, ...)
	/Users/snappj/work/go-work/src/github.com/jeremiahsnapp/chef-load/chef-client-run.go:138 +0xc05
created by main.main
	/Users/snappj/work/go-work/src/github.com/jeremiahsnapp/chef-load/main.go:126 +0x75c
```

**Comment by jeremiahsnapp** [comment]
this should be fixed by https://github.com/chef/chef-load/commit/f5da53d8906ec32655acb1c0bb4f61ef98bd8fe6 released in version 2.2.0
